name: Build and push python image to gcp platform in artifact registery
on :
  push:
    - branches: docker/docker_assignment
jobs:
  build-push-gcr:
    name: Build and push python image to gcp platform in artifact registery
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ggtrend
      PROJECT_ID: sublime-vial-365809
    steps:
    - name: checkout
      uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

    - name: Build docker Image
      run: |
        docker build -t $IMAGE_NAME .

    - name: configure docker client
      run: |
        gcloud auth configure-dockek --quiet 

    - name: push docker image to gcr container registery
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        